name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: fix orientation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cp "${GITHUB_WORKSPACE}/.github/workflows/test.jpg" "${GITHUB_WORKSPACE}/share"
      - run: make build
      - run: make run
      - run: test -f share/test_xmp.jpg
      - uses: actions/upload-artifact@master
        with:
          path: share/*.jpg
